### ISSUE TITLE
Suggestions and acknowledgments

### ISSUE THREAD

**Issue by codedit334** [ernestmusong/Emmacroy-Technologies#2]
@codedit334: Adjust layout to 786px and 1024px of width (Program and People sections), Website looks good overall.

@ZewdieMc: 

@Yosefgeda: Change the closing button color from Mobile Menu, everything else is good. (Hint: use &times;).

**Comment by jeanbuhendwa** [comment]
### Hello @ernestmusong 

- [ ] Please remove the commented line of code in your index.html file to make your code clean 
https://github.com/ernestmusong/Capstone/blob/9eb4e8c5c34392d4b77df0c5244d59f8ed911e9e/index.html#L50

- [ ] Kindly fix the alignment of the `show more` button in your feature speaker section 
<img width="155" alt="Screenshot 2023-03-07 at 10 21 49" src="https://user-images.githubusercontent.com/57327352/223352736-c6fe7ea5-cc54-4f03-b9cd-c1c4e774f1b9.png">
